plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'com.gradleup.shadow' version '9.5.1'
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

repositories {
    mavenCentral()
}

javafx {
    version = '17.0.7'
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

application {
    mainClass.set("Launcher")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

shadowJar {
    archiveBaseName = "javafx-tutorial-duke"
    archiveClassifier = null
}
